name: Run Playwright Scraper

on:
  push:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci || npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Scraper - 23f3001927@ds.study.iitm.ac.in
        run: node scrape.js
